### ISSUE TITLE
Siblings seem to cause layout errors

### ISSUE THREAD

**Issue by dconlan** [phenotips/open-pedigree#5] opened 2019-11-18 05:34 UTC
If you import a simple (fixed, see issue 4) PED with two parents and 2 children 
```
F1 Proband Father Mother 1 -9
F1 Mother 0 0 2 -9
F1 Father 0 0 1 -9
F1 Sister Father Mother 2 -9
```
You get a console full of errors  like this:
```
Error: <path> attribute d: Expected number, "MNaN,272LNaN,215L…"
```
because it seems to have made some nodes have a position of NaN.
All of the nodes appear on top of each other, and scaling/panning doesn't work.
![Screenshot from 2019-11-18 15-31-28](https://user-images.githubusercontent.com/8952947/69026954-cd6a2580-0a18-11ea-935c-a4a73134f7b4.png)

**Comment by buske** [comment] 2019-12-10 05:54
I was unable to reproduce this in Firefox, but was able to reproduce it in Chrome.
This appears to be the same issue as this: https://github.com/phenotips/phenotips/issues/1209

**Comment by buske** [comment] 2019-12-10 05:58
Marking this as closed, but please re-open if this issue persists, @dconlan. Thanks again for flagging this!

**Closed by buske** 2019-12-10 05:58 UTC
